# Generated by Django 4.2.19 on 2025-02-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPosition',
            fields=[
                ('car_pos_id', models.IntegerField(primary_key=True, serialize=False)),
                ('LU_x_coord', models.IntegerField()),
                ('LU_y_coord', models.IntegerField()),
                ('RD_x_coord', models.IntegerField()),
                ('RD_y_coord', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('free_time', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_parking', models.BooleanField(default=False)),
                ('car_pos_id', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
